/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_management_system;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class computer_Allocation extends javax.swing.JFrame {

    /**
     * Creates new form computer_Allocation
     */
    public computer_Allocation() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        section_CB = new javax.swing.JComboBox<>();
        class_CB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Abs_list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        total_list = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_new_cl = new javax.swing.JButton();
        allocate_btn = new javax.swing.JButton();
        show_btn = new javax.swing.JButton();
        move_to_abs = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Allocation");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        section_CB.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        section_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Section", "A", "B", "C" }));
        section_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                section_CBActionPerformed(evt);
            }
        });
        getContentPane().add(section_CB);
        section_CB.setBounds(200, 30, 190, 30);

        class_CB.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        class_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class", "6", "7", "8", "9", "10", "11", "12" }));
        class_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_CBActionPerformed(evt);
            }
        });
        getContentPane().add(class_CB);
        class_CB.setBounds(20, 30, 160, 30);

        Abs_list.setBackground(new java.awt.Color(0, 0, 0));
        Abs_list.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Abs_list.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(Abs_list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(580, 160, 250, 160);

        total_list.setBackground(new java.awt.Color(0, 0, 0));
        total_list.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        total_list.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(total_list);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 120, 320, 410);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Absent Students");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 120, 170, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Students");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 80, 150, 30);

        add_new_cl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        add_new_cl.setText("Add new Class/Student");
        add_new_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_clActionPerformed(evt);
            }
        });
        getContentPane().add(add_new_cl);
        add_new_cl.setBounds(360, 330, 220, 40);

        allocate_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        allocate_btn.setText("Allocate Computers");
        allocate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocate_btnActionPerformed(evt);
            }
        });
        getContentPane().add(allocate_btn);
        allocate_btn.setBounds(600, 330, 220, 40);

        show_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        show_btn.setText("Show Students List");
        show_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_btnActionPerformed(evt);
            }
        });
        getContentPane().add(show_btn);
        show_btn.setBounds(410, 30, 220, 40);

        move_to_abs.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        move_to_abs.setText("Move to Absent List >");
        move_to_abs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                move_to_absActionPerformed(evt);
            }
        });
        getContentPane().add(move_to_abs);
        move_to_abs.setBounds(350, 170, 220, 25);

        reset_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn);
        reset_btn.setBounds(350, 240, 220, 25);

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(490, 400, 220, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1470, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultListModel jListOneModel = new DefaultListModel();
    DefaultListModel jListTwoModel = new DefaultListModel();
    private void show_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_btnActionPerformed
        jListOneModel.removeAllElements();
        total_list.setModel(jListOneModel);
        String cl = (String) class_CB.getSelectedItem();
        String sc = (String) section_CB.getSelectedItem();
        cl = cl.concat(sc);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management", "root", "root");
            Statement st = con.createStatement();
            String qry = "select concat(Rollno,' ) ',Name) from " + cl + ";";
            ResultSet rs = st.executeQuery(qry);
              while (rs.next()) {
                String nam_rl = rs.getString(1);
                jListOneModel.addElement(nam_rl);
            }
            total_list.setModel(jListOneModel);
            move_to_abs.setEnabled(true);
             reset_btn.setEnabled(true);
              allocate_btn.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Given class is not available in database");
        }

    }//GEN-LAST:event_show_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Allocated_computers info = new Allocated_computers();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void move_to_absActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_move_to_absActionPerformed
        if (total_list.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "No Student Selected");
        } else {
            List list = total_list.getSelectedValuesList();
            Object ss[] = list.toArray();
            for (int i = 0; i < list.size(); i++) {
                jListTwoModel.addElement(ss[i]);
            }
            Abs_list.setModel(jListTwoModel);
                if (jListOneModel.getSize() != 0) {
                for (int j = 0; j < list.size(); j++) {
                    jListOneModel.removeElement(ss[j]);
                }
            }
            total_list.setModel(jListOneModel);
        }
    }//GEN-LAST:event_move_to_absActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        String cl = (String) class_CB.getSelectedItem();
        String sc = (String) section_CB.getSelectedItem();
        cl = cl.concat(sc);
        jListOneModel.removeAllElements();
        total_list.setModel(jListOneModel);
        jListTwoModel.removeAllElements();
        Abs_list.setModel(jListTwoModel);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management", "root", "root");
            Statement st = con.createStatement();
            String qry = "select concat(Rollno,' ) ',Name) from " + cl + ";";
            ResultSet rs = st.executeQuery(qry);

            while (rs.next()) {
                String nam_rl = rs.getString(1);
                jListOneModel.addElement(nam_rl);
            }
            total_list.setModel(jListOneModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_reset_btnActionPerformed

    private void add_new_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_clActionPerformed
        add_class_student abc = new add_class_student();
        abc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_new_clActionPerformed

    private void allocate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocate_btnActionPerformed
        DefaultListModel l1 = new DefaultListModel();
        l1 = (DefaultListModel) total_list.getModel();
        String classc = (String) class_CB.getSelectedItem();
        String sectc = (String) section_CB.getSelectedItem();
        String classt = classc.concat(sectc);
        
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management", "root", "root");
            Statement st = con.createStatement();
            int i = 0;
            while (i < l1.size()) {
                String name = (String) l1.get(i);
                String roll = name.substring(0, 2);
                String Name = name.substring(4);
                Name = Name.trim();
                String query = "select DOB from " + classt + " where Name = '" + Name + "' and Rollno = " + roll + ";";
                ResultSet rs = st.executeQuery(query);
                rs.next();
                String dob = rs.getString(1);
                String qry = "insert into computer_allocation values(" + classc + ",'" + sectc + "'," + roll + ",'" + Name + "','present','" + dob + "');";
                st.executeUpdate(qry);
                ++i;
            }
            Allocated_computers ac = new Allocated_computers();
            ac.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_allocate_btnActionPerformed

    private void class_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_CBActionPerformed
        jListOneModel.removeAllElements();
        jListTwoModel.removeAllElements();
        total_list.setModel(jListOneModel);
        Abs_list.setModel(jListTwoModel);
        show_btn.setEnabled(true);
        allocate_btn.setEnabled(false);
        move_to_abs.setEnabled(false);
        reset_btn.setEnabled(false);
    }//GEN-LAST:event_class_CBActionPerformed

    private void section_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_section_CBActionPerformed
        jListOneModel.removeAllElements();
        jListTwoModel.removeAllElements();
        total_list.setModel(jListOneModel);
        Abs_list.setModel(jListTwoModel);
        show_btn.setEnabled(true);
    }//GEN-LAST:event_section_CBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int cb_enter = 0;
        jLabel1.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        ImageIcon i = (new ImageIcon(getClass().getResource("648552.jpg")));
        Image img = i.getImage();
        Image k = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon l = new ImageIcon(k);
        jLabel1.setIcon(l);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        class_CB.removeAllItems();
        section_CB.removeAllItems();
        class_CB.addItem("Select Class");
        section_CB.addItem("Select Section");
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management", "root", "root");
            Statement stm = con.createStatement();
            Statement stmm = con.createStatement();
            String qry = "show tables;";
            ResultSet rs = stmm.executeQuery(qry);
            while (rs.next()) {
               String len = rs.getString(1);
                int length = len.length();
                
              if (length == 3) {
                  String qryy = "insert into comboaddtableandsection values("+len.substring(0,2)+",'"+len.substring(2).toUpperCase()+"');";
                  stm.executeUpdate(qryy);
                }
              else if(length == 2)
              {
          String qryy = "insert into comboaddtableandsection values("+len.substring(0,1)+",'"+len.substring(1).toUpperCase()+"');";
             stm.executeUpdate(qryy);
              }
            }
            Statement st = con.createStatement();
             ResultSet rt = st.executeQuery("select distinct(t_name) from comboaddtableandsection order by t_name;");
             while(rt.next())
             {
            class_CB.addItem(rt.getString(1));
            }
             Statement su = con.createStatement();
             ResultSet ru = su.executeQuery("select distinct(section) from comboaddtableandsection order by section");
             while(ru.next())
             {
             section_CB.addItem(ru.getString(1));
             }
             String query = "delete from comboaddtableandsection;";
            stm.executeUpdate(query);
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
del_and_report();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(computer_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(computer_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(computer_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(computer_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new computer_Allocation().setVisible(true);
            }
        });
    }
private void del_and_report()
{
try
{
Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management","root","root");
Statement d = cn.createStatement();
String send = "select * from temp";
ResultSet b = d.executeQuery(send);
Statement de = cn.createStatement();
Statement ed = cn.createStatement();
ResultSet rs = ed.executeQuery("select Name from login_info");
rs.next();
String usr = rs.getString(1);
if(b.next())
{
 b.beforeFirst();
while(b.next())
{
int rno = b.getInt(1);
String nm = b.getString(2);
String cname = b.getString(3);
int clss = b.getInt(5);
String sn = b.getString(6);
String exec= "insert into stu_report values("+clss+",'"+sn+"',"+rno+",'"+nm+"','"+cname+"',sysdate(),'"+usr+"');";
de.executeUpdate(exec);
}
String del = "delete from temp;";
String log_del = "delete from login_info;";
de.executeUpdate(del);
de.executeUpdate(log_del);
}
else
{
String log_del = "delete from login_info;";
de.executeUpdate(log_del);
}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,e.getMessage());
}

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Abs_list;
    private javax.swing.JButton add_new_cl;
    private javax.swing.JButton allocate_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JComboBox<String> class_CB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton move_to_abs;
    private javax.swing.JButton reset_btn;
    private javax.swing.JComboBox<String> section_CB;
    private javax.swing.JButton show_btn;
    private javax.swing.JList<String> total_list;
    // End of variables declaration//GEN-END:variables
}
