/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class forgot_pass extends javax.swing.JFrame {

    /**
     * Creates new form reset_password
     */
    public forgot_pass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_ID_TF = new javax.swing.JTextField();
        Name_TF = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        Password_Field2 = new javax.swing.JPasswordField();
        reset_pass_btn = new javax.swing.JButton();
        Check_details_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Reset");
        setMinimumSize(new java.awt.Dimension(650, 515));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        User_ID_TF.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        User_ID_TF.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(User_ID_TF);
        User_ID_TF.setBounds(300, 170, 300, 40);

        Name_TF.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Name_TF.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(Name_TF);
        Name_TF.setBounds(300, 120, 300, 40);

        password_field.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        password_field.setForeground(new java.awt.Color(255, 153, 0));
        password_field.setEchoChar('*');
        getContentPane().add(password_field);
        password_field.setBounds(360, 290, 210, 40);

        Password_Field2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Password_Field2.setForeground(new java.awt.Color(255, 153, 0));
        Password_Field2.setEchoChar('*');
        getContentPane().add(Password_Field2);
        Password_Field2.setBounds(360, 370, 210, 40);

        reset_pass_btn.setBackground(new java.awt.Color(51, 51, 51));
        reset_pass_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        reset_pass_btn.setForeground(new java.awt.Color(255, 153, 0));
        reset_pass_btn.setText("Reset Password");
        reset_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_pass_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_pass_btn);
        reset_pass_btn.setBounds(360, 430, 190, 30);

        Check_details_btn.setBackground(new java.awt.Color(51, 51, 51));
        Check_details_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Check_details_btn.setForeground(new java.awt.Color(255, 153, 0));
        Check_details_btn.setText("Check Details");
        Check_details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_details_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Check_details_btn);
        Check_details_btn.setBounds(360, 233, 150, 30);

        back_btn.setBackground(new java.awt.Color(51, 51, 51));
        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 153, 0));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(60, 430, 71, 25);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("<html><u>Enter new password:-</u></html>");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 290, 290, 40);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("<html><u>Enter Your details Below:-</u></html>");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 30, 340, 40);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("<html><u>Re-enter new password:-</u></html>");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 370, 330, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("<html><u>Enter UserID:-</u></html>");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 250, 40);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("<html><u>Enter Name:-</u></html>");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 120, 250, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab_management_system/2751.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        password_field.setEnabled(false);
        Password_Field2.setEnabled(false);
        reset_pass_btn.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void Check_details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_details_btnActionPerformed
        String name = Name_TF.getText();
        String UID = User_ID_TF.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management", "root", "root");
            Statement stmt = con.createStatement();
            String qry = "select * from admin_id where Name = '" + name + "' and UserID = '" + UID + "';";
            if (Name_TF.getText().equals(null) || User_ID_TF.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Details are not filled.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                ResultSet rs = stmt.executeQuery(qry);
                if (rs.next()) {
                    password_field.setEnabled(true);
                    Password_Field2.setEnabled(true);
                    reset_pass_btn.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Enter your new password!");
                    Name_TF.setEnabled(false);
                    User_ID_TF.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Name or UserID did not matched.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_Check_details_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Login_page info = new Login_page();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void reset_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_pass_btnActionPerformed
        String name = Name_TF.getText();
        String pass = password_field.getText();
        String UID = User_ID_TF.getText();
        String pass_confirm = Password_Field2.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management", "root", "root");
            Statement stmt = con.createStatement();
            if (pass.matches(pass_confirm) == false) {
                JOptionPane.showMessageDialog(null, "Password not matched");
            } else {
                String sw = JOptionPane.showInputDialog(null, "Enter Security Word:");
                String word = "select * from admin_id where Security_word = '"+sw+"' and UserID = '"+UID+"';";
                String qry = "update admin_id set Password = '" + pass + "' where UserID = '" + UID + "' and Security_word = '"+sw+"';";
                ResultSet rs = stmt.executeQuery(word);
                if (rs.next()) {
                    stmt.executeUpdate(qry);
                    JOptionPane.showMessageDialog(null, "Password Reset Successfull");
                    Login_page info = new Login_page();
                    info.setVisible(true);
                    this.dispose();
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Invalid Security Word", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_reset_pass_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Check_details_btn;
    private javax.swing.JTextField Name_TF;
    private javax.swing.JPasswordField Password_Field2;
    private javax.swing.JTextField User_ID_TF;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JButton reset_pass_btn;
    // End of variables declaration//GEN-END:variables
}
