/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Login_page extends javax.swing.JFrame {

    /**
     * Creates new form Login_page
     */
    public Login_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Forgot_pass = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        Exit_Btn = new javax.swing.JButton();
        Register_Btn = new javax.swing.JButton();
        Login_Btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setMinimumSize(new java.awt.Dimension(650, 520));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Enter Username:-");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 240, 40);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Enter Password:-");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 290, 240, 40);

        Forgot_pass.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Forgot_pass.setForeground(new java.awt.Color(0, 153, 255));
        Forgot_pass.setText("<html><b><u>Forgot Password</u></b>");
        Forgot_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Forgot_passMouseClicked(evt);
            }
        });
        getContentPane().add(Forgot_pass);
        Forgot_pass.setBounds(470, 330, 130, 20);

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 210, 300, 40);

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(300, 290, 310, 40);

        Exit_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Exit_Btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Exit_Btn.setForeground(new java.awt.Color(0, 153, 255));
        Exit_Btn.setText("Exit");
        Exit_Btn.setOpaque(false);
        Exit_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Btn);
        Exit_Btn.setBounds(70, 380, 130, 40);

        Register_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Register_Btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Register_Btn.setForeground(new java.awt.Color(0, 153, 255));
        Register_Btn.setText("Register");
        Register_Btn.setOpaque(false);
        Register_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Register_Btn);
        Register_Btn.setBounds(230, 380, 130, 40);

        Login_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Login_Btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Login_Btn.setForeground(new java.awt.Color(0, 153, 255));
        Login_Btn.setText("Login");
        Login_Btn.setOpaque(false);
        Login_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Login_Btn);
        Login_Btn.setBounds(400, 380, 130, 40);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><u> Welcome!<br>Login Here</u>");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 30, 300, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab_management_system/2751.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Forgot_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Forgot_passMouseClicked
       forgot_pass F_p = new forgot_pass();
       F_p.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Forgot_passMouseClicked

    private void Exit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_BtnActionPerformed
    System.exit(0);
    }//GEN-LAST:event_Exit_BtnActionPerformed

    private void Login_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BtnActionPerformed
       String user_nm = jTextField1.getText();
       String pass_wd = jPasswordField1.getText();
       try
       {
       Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Lab_management","root","root");
       Statement st = con.createStatement();
       String qry = "select * from admin_ID where UserID = '"+user_nm+"' and Password = '"+pass_wd+"';";
       ResultSet rs = st.executeQuery(qry);
       if(rs.next())
       {
       String query = "insert into login_info values('"+rs.getString(1)+"','"+rs.getString(2)+"','"+rs.getString(3)+"','"+rs.getString(4)+"','"+rs.getString(5)+"');";    
       JOptionPane.showMessageDialog(null,"Congratulations! you have logged in successfully.");
       st.executeUpdate(query);
       Allocated_computers A_c = new Allocated_computers();
       A_c.setVisible(true);
       this.dispose();
       }
       else
       {
       JOptionPane.showMessageDialog(null,"Invalid Username or Password.","Error",JOptionPane.ERROR_MESSAGE);
       }
       }
       catch(Exception e)
       {
       JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_Login_BtnActionPerformed

    private void Register_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_BtnActionPerformed
register_admin n = new register_admin();
n.setVisible(true);
this.dispose();
    }//GEN-LAST:event_Register_BtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try 
{
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management", "root", "root");
    Statement stm = con.createStatement();
    stm.executeUpdate("delete from temp;");
    stm.executeUpdate("delete from computer_allocation;");
    stm.executeUpdate("delete from login_info;");
    stm.executeUpdate("delete from comboaddtableandsection;");
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null, "An Error Occured Please Retry.");
}
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_Btn;
    private javax.swing.JLabel Forgot_pass;
    private javax.swing.JButton Login_Btn;
    private javax.swing.JButton Register_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
