/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class register_admin extends javax.swing.JFrame {

    /**
     * Creates new form register_admin
     */
    public register_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nm = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        pwd_con = new javax.swing.JPasswordField();
        mg = new javax.swing.JRadioButton();
        fg = new javax.swing.JRadioButton();
        og = new javax.swing.JRadioButton();
        sec_word = new javax.swing.JTextField();
        Register_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Page");
        setMinimumSize(new java.awt.Dimension(630, 515));
        setResizable(false);
        getContentPane().setLayout(null);

        nm.setBackground(new java.awt.Color(51, 51, 51));
        nm.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        nm.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(nm);
        nm.setBounds(220, 90, 290, 30);

        id.setBackground(new java.awt.Color(51, 51, 51));
        id.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(id);
        id.setBounds(250, 140, 260, 30);

        pwd.setBackground(new java.awt.Color(51, 51, 51));
        pwd.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        pwd.setForeground(new java.awt.Color(0, 153, 255));
        pwd.setEchoChar('*');
        getContentPane().add(pwd);
        pwd.setBounds(250, 190, 280, 30);

        pwd_con.setBackground(new java.awt.Color(51, 51, 51));
        pwd_con.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        pwd_con.setForeground(new java.awt.Color(0, 153, 255));
        pwd_con.setEchoChar('*');
        getContentPane().add(pwd_con);
        pwd_con.setBounds(290, 240, 280, 30);

        mg.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(mg);
        mg.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        mg.setForeground(new java.awt.Color(51, 153, 255));
        mg.setText("Male");
        mg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgActionPerformed(evt);
            }
        });
        getContentPane().add(mg);
        mg.setBounds(230, 290, 71, 30);

        fg.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(fg);
        fg.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        fg.setForeground(new java.awt.Color(51, 153, 255));
        fg.setText("Female");
        fg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fgActionPerformed(evt);
            }
        });
        getContentPane().add(fg);
        fg.setBounds(340, 290, 110, 30);

        og.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(og);
        og.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        og.setForeground(new java.awt.Color(51, 153, 255));
        og.setText("Others");
        og.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogActionPerformed(evt);
            }
        });
        getContentPane().add(og);
        og.setBounds(490, 290, 110, 29);

        sec_word.setBackground(new java.awt.Color(51, 51, 51));
        sec_word.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        sec_word.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(sec_word);
        sec_word.setBounds(290, 340, 140, 30);

        Register_btn.setBackground(new java.awt.Color(51, 51, 51));
        Register_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Register_btn.setForeground(new java.awt.Color(0, 153, 255));
        Register_btn.setText("Register");
        Register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Register_btn);
        Register_btn.setBounds(330, 410, 130, 40);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Enter UserID:-");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 220, 30);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Enter Password:-");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 220, 30);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Re-enter Password:-");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 240, 260, 30);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Enter Name:-");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 290, 180, 30);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Enter Security Word:-");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 340, 270, 30);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Enter Name:-");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 90, 180, 30);

        back_btn.setBackground(new java.awt.Color(51, 51, 51));
        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(0, 153, 255));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(90, 410, 130, 40);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("<html><u>Register Here</u>");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 10, 300, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab_management_system/2751.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents
String gen = "none";
    private void mgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgActionPerformed
        if(mg.isSelected())
        {
            gen= "Male";
        }
    }//GEN-LAST:event_mgActionPerformed

    private void fgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fgActionPerformed
        if(fg.isSelected())
        {
            gen="Female";
        }
    }//GEN-LAST:event_fgActionPerformed

    private void ogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogActionPerformed
        if(og.isSelected())
        {
            gen="Others";
        }
    }//GEN-LAST:event_ogActionPerformed

    private void Register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_btnActionPerformed
        String name = nm.getText();
        String usernm = id.getText();
        String password = pwd.getText();
        String pass_confirm = pwd_con.getText();
        String gender = gen;
        String security = sec_word.getText();
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab_management","root","root");
            Statement stmt = con.createStatement();
            String qry = "insert into admin_id values('"+name.trim()+"','"+usernm.trim()+"','"+password.trim()+"','"+gender+"','"+security.trim()+"');";
            if(name.trim().isEmpty() || usernm.trim().isEmpty() || password.trim().isEmpty() ||pass_confirm.trim().isEmpty()
                    ||security.trim().isEmpty() ||gen.equals("none"))
            {
                JOptionPane.showMessageDialog(null,"All details are not filled.","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if(password.matches(pass_confirm)== false)
            {
                JOptionPane.showMessageDialog(null,"Password does not matches.","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if(password.trim().length()<5)
            {
                JOptionPane.showMessageDialog(null,"Password too Short.","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if(password.trim().length()>14)
{
JOptionPane.showMessageDialog(null,"New Password too Long.","Error",JOptionPane.ERROR_MESSAGE);
}
            else
            {   
        
                String confirm = "select * from admin_id where UserID = '"+usernm+"' or Security_word = '"+security+"';";
                ResultSet r = stmt.executeQuery(confirm);
                if(r.next())
                {
                    JOptionPane.showMessageDialog(null,"UserID or Security word already exist");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Please remember your security word because it can't be changed later.");
                    int cof = JOptionPane.showConfirmDialog(null,"Are you sure you want to register","",JOptionPane.YES_NO_OPTION);
                    if(cof == JOptionPane.YES_OPTION)
                    {
                    stmt.executeUpdate(qry);
                    JOptionPane.showMessageDialog(null,"You have been registered successfully");
                    Login_page info = new Login_page();
                    info.setVisible(true);
                    this.dispose();
                    }
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"An Error Occured.Please Retry","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Register_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
Login_page info = new Login_page();
info.setVisible(true);
this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fg;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton mg;
    private javax.swing.JTextField nm;
    private javax.swing.JRadioButton og;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JPasswordField pwd_con;
    private javax.swing.JTextField sec_word;
    // End of variables declaration//GEN-END:variables
}
